openapi: '3.0.0'
info:
  version: '1.0.0'
  title: 'UniBar API'
  description: API definition for interacting with the back-end system.

servers:
  - url: localhost:3000
    description: Local test server.

paths:
  /ping:
    description: Pings the server.
    get:
      responses:
        200:
          description: Successful ping from the server.
  
  /users/register:
    description: Registering a user.
    parameters:
      - name: email
        description: Email of the user to create.
        in: header
        required: true
        schema:
          type: string
      - name: password
        description: Password used for user to sign-in in the future.
        in: header
        required: true
        schema:
          type: string
          format: password
    put:
      summary: Create a new user.
      security:
        - UserToken: []
      responses:
        200:
          description: Successfully registered a new user.
        400:
          description: Failed to register a new user.
        403:
          description: User already exists.
          
  /users/login:
    description: Logging in a user.
    parameters:
      - name: email
        description: User email for logging in.
        in: header
        required: true
        schema:
          $ref: "#/components/schemas/Email"
      - name: password
        description: User password for logging in.
        required: true
        in: header
        schema:
          $ref: "#/components/schemas/Password"
    get:
      summary: Log in a user.
      responses:
        200:
          description: Successfully logged in.
          content:
            user_id:
              schema:
                $ref: "#/components/schemas/UserID"
            user_token:
              schema:
                $ref: "#/components/schemas/UserToken"
        400:
          description: Failed to log in user.

  /user/{user_id}/orders/delivering:
    description: Fetch the user's order that they are delivering.
    parameters:
      - name: user_id
        description: Identifying the user.
        required: true
        in: path
        schema:
          $ref: "#/components/schemas/UserID"
    get:
      security:
        - UserToken: []
      responses:
        200:
          description: Succesfully fetched user's active orders.
          content:
            orders:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Order"
        400:
          description: Failed to fetch user's active delivered orders.

  /user/{user_id}/orders/requesting:
    description: Fetch the user's order that they are requesting.
    parameters:
      - name: user_id
        description: Identifying the user.
        required: true
        in: path
        schema:
          $ref: "#/components/schemas/UserID"
    get:
      security:
        - UserToken: []
      responses:
        200:
          description: Succesfully fetched user's active orders.
          content:
            orders:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Order"
        400:
          description: Failed to fetch user's active delivery requests.

  /user/{user_id}/order/request:
    description: Create a new delivery request.
    parameters:
      - name: user_id
        description: Identifying the user.
        required: true
        in: path
        schema:
          $ref: "#/components/schemas/UserID"
      - name: request
        description: Delivery request of the user.
        required: true
        in: header
        schema:
          $ref: "#/components/schemas/Request"
    put:
      security:
        - UserToken: []
      responses:
        200:
          description: Successfully created a delivery request.
          content:
            request_id:
              schema:
                type: string
        400:
          description: Failed to create a delivery request.

  /user/{user_id}/order/deliver:
    description: Indicate 
    parameters:
      - name: user_id
        description: User to fulfil the order.
        required: true
        in: path
        schema:
          $ref: "#/components/schemas/UserAuth"
      - name: order_id
        description: Order to deliver.
        required: true
        in: header
        schema:
          type: string
    put: 
      security:
        - UserToken: []
      responses:
        200:
          description: Succesfully
        400:
          description: Could not fulfil the order.
        409:
          description: Order is currently being fulfilled.

  /user/{user_id}/token/transfer:
    description: Transfer one token from one user to another.
    parameters:
      - name: user_id
        description: User that is giving the delivery token.
        required: true
        in: path
        schema:
          $ref: "#/components/schemas/UserID"
      - name: receiver
        description: User that is receiving the delivery token.
        required: true
        in: header
        schema:
          $ref: "#/components/schemas/UserID"
      - name: order_id
        description: Order for which the delivery token is being transfered.
        required: true
        in: header
        schema:
          $ref: "#/components/schemas/OrderID"
    put:
      200:
        description: Successfully transfered the token.

  /user/{user_id}/token/remaining:
    description: List the number of tokens remaining for the user.
    parameters:
      - name: user_id
        description: User that is requesting its remaining tokens.
        required: true
        in: path
        schema:
          $ref: "#/components/schemas/UserID"
    get:
      security:
        - UserToken: []
      responses:
        200:
          description: Successfully fetched delivery tokens remaining for the user.
          content:
            tokens:
              schema:
                $ref: "#/components/schemas/Tokens"
      

  /orders/available:
    description: Lists all orders available to fulfill.
    get:
      responses:
        200:
          description: Successfully fetched orders available to fulfill.
          content:
            orders:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Order"
        400:
          description: Failed to fetch orders available to fulfill.

  /orders/{order_id}:
    description: Fetch a specific order.
    parameters:
      - name: order_id
        description: Identification of the order.
        required: true
        in: path
        schema:
          $ref: "#/components/schemas/OrderID"
    get:
      responses:
        200:
          description: Successfully fetched order.
          content:
            order:
              schema:
                $ref: "#/components/schemas/Order"
        400:
          description: Failed to fetch orders.

  /admin/{admin_id}/users/list:
    description: Lists all user IDs.
    parameters:
      - name: admin_id
        description: Identification of the admin.
        required: true
        in: path
        schema:
          $ref: "#/components/schemas/AdminID"
    get:
      security:
        - AdminToken: []
      responses:
        200:
          description: Succesfully fetched all user IDs.
          content:
            user_ids:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/UserID"
        400:
          description: Failed to fetch all user IDs.

  /admin/{admin_id}/user/{user_id}:
    description: Lists specific user information (password & access token redacted).
    parameters:
      - name: admin_id
        description: Identification of the admin.
        required: true
        in: path
        schema:
          $ref: "#/components/schemas/AdminID"
      - name: user_id
        description: User of which to fetch information about.
        required: true
        in: path
        schema:
          $ref: "#/components/schemas/UserID"
    get:
      security:
        - AdminToken: []
      responses:
        200:
          description: Successfully fetched user information.
          content:
            user:
              schema:
                $ref: "#/components/schemas/User"

  /admin/{admin_id}/orders/list:
    description: Lists all order IDs.
    parameters:
      - name: admin_id
        description: Identification of the admin.
        required: true
        in: path
        schema:
          $ref: "#/components/schemas/AdminID"
    get:
      security:
        - AdminToken: []
      responses:
        200:
          description: Succesfully fetched all orders IDs.
          content:
            user_ids:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/OrderID"
        400:
          description: Failed to fetch all order IDs.

components:
  schemas:
    OrderID:
      description: Identification of the order.
    Order:
      description: Content of the order.
      type: object
      properties:
        order_id:
          $ref: "#/components/schemas/OrderID"
        # TODO: complete this order schema
    UserID:
      description: Identification of a user.
      type: string
    Name:
      description: User's display name.
      type: string
    Email:
      description: Email format.
      type: string
      format: email
    Password:
      description: Password format.
      type: string
      format: password
    Tokens:
      description: Delivery token count.
      type: integer
      format: int32
    User:
      description: Public-safe user definition.
      type: object
      properties:
        user_id:
          $ref: "#/components/schemas/UserID"
        name:
          $ref: "#/components/schemas/Name"
        email:
          $ref: "#/components/schemas/Email"
        tokens:
          $ref: "#/components/schemas/Tokens"
    AdminID:
      description: Identification of a admin.
      type: string
  securitySchemes:
    UserToken:
      type: apiKey
      in: header
      name: user_token
    AdminToken:
      type: apiKey
      in: header
      name: admin_token