# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class BodyAdminLogin(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, admin_token=None):  # noqa: E501
        """BodyAdminLogin - a model defined in OpenAPI

        :param admin_token: The admin_token of this BodyAdminLogin.  # noqa: E501
        :type admin_token: str
        """
        self.openapi_types = {
            'admin_token': str
        }

        self.attribute_map = {
            'admin_token': 'admin_token'
        }

        self._admin_token = admin_token

    @classmethod
    def from_dict(cls, dikt) -> 'BodyAdminLogin':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_object_8 of this BodyAdminLogin.  # noqa: E501
        :rtype: BodyAdminLogin
        """
        return util.deserialize_model(dikt, cls)

    @property
    def admin_token(self):
        """Gets the admin_token of this BodyAdminLogin.


        :return: The admin_token of this BodyAdminLogin.
        :rtype: str
        """
        return self._admin_token

    @admin_token.setter
    def admin_token(self, admin_token):
        """Sets the admin_token of this BodyAdminLogin.


        :param admin_token: The admin_token of this BodyAdminLogin.
        :type admin_token: str
        """
        if admin_token is None:
            raise ValueError("Invalid value for `admin_token`, must not be `None`")  # noqa: E501

        self._admin_token = admin_token
