# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
import re
from openapi_server import util

import re  # noqa: E501

class BodyUserUpdate(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, name=None, password=None, phone_number=None, etransfer_email=None):  # noqa: E501
        """BodyUserUpdate - a model defined in OpenAPI

        :param name: The name of this BodyUserUpdate.  # noqa: E501
        :type name: str
        :param password: The password of this BodyUserUpdate.  # noqa: E501
        :type password: str
        :param phone_number: The phone_number of this BodyUserUpdate.  # noqa: E501
        :type phone_number: str
        :param etransfer_email: The etransfer_email of this BodyUserUpdate.  # noqa: E501
        :type etransfer_email: str
        """
        self.openapi_types = {
            'name': str,
            'password': str,
            'phone_number': str,
            'etransfer_email': str
        }

        self.attribute_map = {
            'name': 'name',
            'password': 'password',
            'phone_number': 'phone_number',
            'etransfer_email': 'etransfer_email'
        }

        self._name = name
        self._password = password
        self._phone_number = phone_number
        self._etransfer_email = etransfer_email

    @classmethod
    def from_dict(cls, dikt) -> 'BodyUserUpdate':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_object_3 of this BodyUserUpdate.  # noqa: E501
        :rtype: BodyUserUpdate
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self):
        """Gets the name of this BodyUserUpdate.

        User's display name.  # noqa: E501

        :return: The name of this BodyUserUpdate.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this BodyUserUpdate.

        User's display name.  # noqa: E501

        :param name: The name of this BodyUserUpdate.
        :type name: str
        """

        self._name = name

    @property
    def password(self):
        """Gets the password of this BodyUserUpdate.

        Password format.  # noqa: E501

        :return: The password of this BodyUserUpdate.
        :rtype: str
        """
        return self._password

    @password.setter
    def password(self, password):
        """Sets the password of this BodyUserUpdate.

        Password format.  # noqa: E501

        :param password: The password of this BodyUserUpdate.
        :type password: str
        """

        self._password = password

    @property
    def phone_number(self):
        """Gets the phone_number of this BodyUserUpdate.

        Phone number format.  # noqa: E501

        :return: The phone_number of this BodyUserUpdate.
        :rtype: str
        """
        return self._phone_number

    @phone_number.setter
    def phone_number(self, phone_number):
        """Sets the phone_number of this BodyUserUpdate.

        Phone number format.  # noqa: E501

        :param phone_number: The phone_number of this BodyUserUpdate.
        :type phone_number: str
        """
        if phone_number is not None and not re.search(r'^\d{10}$', phone_number):  # noqa: E501
            raise ValueError("Invalid value for `phone_number`, must be a follow pattern or equal to `/^\d{10}$/`")  # noqa: E501

        self._phone_number = phone_number

    @property
    def etransfer_email(self):
        """Gets the etransfer_email of this BodyUserUpdate.

        Email format.  # noqa: E501

        :return: The etransfer_email of this BodyUserUpdate.
        :rtype: str
        """
        return self._etransfer_email

    @etransfer_email.setter
    def etransfer_email(self, etransfer_email):
        """Sets the etransfer_email of this BodyUserUpdate.

        Email format.  # noqa: E501

        :param etransfer_email: The etransfer_email of this BodyUserUpdate.
        :type etransfer_email: str
        """

        self._etransfer_email = etransfer_email
