# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class BodyOrderReport(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, order_id=None, reported_id=None, message=None):  # noqa: E501
        """BodyOrderReport - a model defined in OpenAPI

        :param order_id: The order_id of this BodyOrderReport.  # noqa: E501
        :type order_id: str
        :param reported_id: The reported_id of this BodyOrderReport.  # noqa: E501
        :type reported_id: str
        :param message: The message of this BodyOrderReport.  # noqa: E501
        :type message: str
        """
        self.openapi_types = {
            'order_id': str,
            'reported_id': str,
            'message': str
        }

        self.attribute_map = {
            'order_id': 'order_id',
            'reported_id': 'reported_id',
            'message': 'message'
        }

        self._order_id = order_id
        self._reported_id = reported_id
        self._message = message

    @classmethod
    def from_dict(cls, dikt) -> 'BodyOrderReport':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_object_6 of this BodyOrderReport.  # noqa: E501
        :rtype: BodyOrderReport
        """
        return util.deserialize_model(dikt, cls)

    @property
    def order_id(self):
        """Gets the order_id of this BodyOrderReport.

        Identification of the order.  # noqa: E501

        :return: The order_id of this BodyOrderReport.
        :rtype: str
        """
        return self._order_id

    @order_id.setter
    def order_id(self, order_id):
        """Sets the order_id of this BodyOrderReport.

        Identification of the order.  # noqa: E501

        :param order_id: The order_id of this BodyOrderReport.
        :type order_id: str
        """
        if order_id is None:
            raise ValueError("Invalid value for `order_id`, must not be `None`")  # noqa: E501

        self._order_id = order_id

    @property
    def reported_id(self):
        """Gets the reported_id of this BodyOrderReport.

        Identification of a user.  # noqa: E501

        :return: The reported_id of this BodyOrderReport.
        :rtype: str
        """
        return self._reported_id

    @reported_id.setter
    def reported_id(self, reported_id):
        """Sets the reported_id of this BodyOrderReport.

        Identification of a user.  # noqa: E501

        :param reported_id: The reported_id of this BodyOrderReport.
        :type reported_id: str
        """
        if reported_id is None:
            raise ValueError("Invalid value for `reported_id`, must not be `None`")  # noqa: E501

        self._reported_id = reported_id

    @property
    def message(self):
        """Gets the message of this BodyOrderReport.


        :return: The message of this BodyOrderReport.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message):
        """Sets the message of this BodyOrderReport.


        :param message: The message of this BodyOrderReport.
        :type message: str
        """
        if message is None:
            raise ValueError("Invalid value for `message`, must not be `None`")  # noqa: E501

        self._message = message
