# coding: utf-8

from __future__ import absolute_import
from datetime import datetime, timezone  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class Message(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, message_id=None, user_id=None, email=None, message=None, time=None):  # noqa: E501
        """Message - a model defined in OpenAPI

        :param message_id: The message_id of this Message.  # noqa: E501
        :type message_id: str
        :param user_id: The user_id of this Message.  # noqa: E501
        :type user_id: str
        :param email: The email of this Message.  # noqa: E501
        :type email: str
        :param message: The message of this Message.  # noqa: E501
        :type message: str
        :param time: The time of this Message.  # noqa: E501
        :type time: datetime
        """
        self.openapi_types = {
            'message_id': str,
            'user_id': str,
            'email': str,
            'message': str,
            'time': datetime
        }

        self.attribute_map = {
            'message_id': 'message_id',
            'user_id': 'user_id',
            'email': 'email',
            'message': 'message',
            'time': 'time'
        }

        self._message_id = message_id
        self._user_id = user_id
        self._email = email
        self._message = message
        self._time = time.replace(tzinfo=timezone.utc) if not None else None

    @classmethod
    def from_dict(cls, dikt) -> 'Message':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Message of this Message.  # noqa: E501
        :rtype: Message
        """
        return util.deserialize_model(dikt, cls)

    @property
    def message_id(self):
        """Gets the message_id of this Message.


        :return: The message_id of this Message.
        :rtype: str
        """
        return self._message_id

    @message_id.setter
    def message_id(self, message_id):
        """Sets the message_id of this Message.


        :param message_id: The message_id of this Message.
        :type message_id: str
        """

        self._message_id = message_id

    @property
    def user_id(self):
        """Gets the user_id of this Message.

        Identification of a user.  # noqa: E501

        :return: The user_id of this Message.
        :rtype: str
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id):
        """Sets the user_id of this Message.

        Identification of a user.  # noqa: E501

        :param user_id: The user_id of this Message.
        :type user_id: str
        """

        self._user_id = user_id

    @property
    def email(self):
        """Gets the email of this Message.

        Email format.  # noqa: E501

        :return: The email of this Message.
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email):
        """Sets the email of this Message.

        Email format.  # noqa: E501

        :param email: The email of this Message.
        :type email: str
        """

        self._email = email

    @property
    def message(self):
        """Gets the message of this Message.


        :return: The message of this Message.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message):
        """Sets the message of this Message.


        :param message: The message of this Message.
        :type message: str
        """

        self._message = message

    @property
    def time(self):
        """Gets the time of this Message.


        :return: The time of this Message.
        :rtype: datetime
        """
        return self._time

    @time.setter
    def time(self, time):
        """Sets the time of this Message.


        :param time: The time of this Message.
        :type time: datetime
        """

        self._time = time.replace(tzinfo=timezone.utc) if not None else None
